#!/usr/bin/env bash
# Rebuild docs/index.html from HTML files in docs/visual-explainer/.
set -euo pipefail

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
explainer_dir="$repo_root/docs/visual-explainer"
index_path="$repo_root/docs/index.html"

html_escape() {
  python3 -c 'import html,sys; print(html.escape(sys.stdin.read().rstrip("\n")))'
}

page_title() {
  local file="$1"
  local title
  title="$(python3 - "$file" <<'PY'
import re, sys
from pathlib import Path
text = Path(sys.argv[1]).read_text(encoding="utf-8", errors="replace")
match = re.search(r"<title>(.*?)</title>", text, flags=re.IGNORECASE | re.DOTALL)
if not match:
    sys.exit(0)
title = re.sub(r"\s+", " ", match.group(1)).strip()
print(title)
PY
)"
  if [[ -n "$title" ]]; then
    printf '%s' "$title"
  else
    basename "$file" .html
  fi
}

items=""
shopt -s nullglob
pages=("$explainer_dir"/*.html)
if ((${#pages[@]})); then
  # Sort by filename so the listing is stable across machines.
  mapfile -t pages < <(printf '%s\n' "${pages[@]}" | LC_ALL=C sort)
  for page in "${pages[@]}"; do
    name="$(basename "$page")"
    [[ "$name" == "index.html" ]] && continue
    title="$(page_title "$page" | html_escape)"
    href="visual-explainer/$(printf '%s' "$name" | html_escape)"
    items+="        <li><a href=\"${href}\">${title}</a></li>"$'\n'
  done
fi
shopt -u nullglob

if [[ -z "$items" ]]; then
  listing='        <li>No visual explainers yet.</li>'
else
  listing="${items%$'\n'}"
fi

cat > "$index_path" <<EOF
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>rmf visual explainers</title>
  <style>
    :root { color-scheme: light dark; }
    body {
      font-family: "Iowan Old Style", "Palatino Linotype", Palatino, Georgia, serif;
      line-height: 1.5;
      max-width: 40rem;
      margin: 4rem auto;
      padding: 0 1.5rem;
    }
    h1 { font-size: 1.75rem; font-weight: 600; }
    p { color: CanvasText; }
    ul { padding-left: 1.2rem; }
    a { color: inherit; }
    code { font-family: ui-monospace, "Cascadia Code", "Source Code Pro", Menlo, monospace; font-size: 0.9em; }
  </style>
</head>
<body>
  <h1>rmf visual explainers</h1>
  <p>HTML pages generated by visual-explainer live in <code>docs/visual-explainer/</code> and publish here on push to <code>main</code>.</p>
  <ul>
${listing}
  </ul>
</body>
</html>
EOF
